### PR TITLE
Feature/kick es6 promise in favour of anypromise

### PR DESCRIPTION
**Pull request by layflags**
Hi Terin, 

I really need this any-promise thingy, because I want to have a super small build for my project.

This branch was tested with Karma on an old Chromium v28 which lacks native Promise support. To make this work I added [Karma Promise](https://github.com/nsappsteam/karma-promise) as a dev dependency.

So this PR implements #4

Cheers,
Lay

### CODE REVIEW

**Comment by layflags** [comment]
This should be a breaking change at least for old Node versions (prior 0.12) and old Browsers (<= IE11, etc.). So I recommend bumping the major version for the next release.

**Comment by layflags** [comment]
@terinjokes any chance to merge this PR?

**Comment by terinjokes** [comment]
@layflags Looks like my changes today caused a merge conflict. I have to do some errands today, but I'll try to merge this branch manually this afternoon. It's a pretty straight-forward PR, so shouldn't be any difficulties.

**Comment by layflags** [comment]
Nice! :)

**Comment by terinjokes** [comment]
@layflags Can you take a gander at the above linked commit and tell me if it works for you. I plan on releasing it as 2.0.0.

**Comment by layflags** [comment]
I resolved the issues manually ... let's see what travis says ;)

**Comment by terinjokes** [comment]
@layflags I wasn't going to merge this PR. I have an alternative branch I wanted you to review.

**Comment by layflags** [comment]
@terinjokes Got it, looks good.

**Pull request closed without merging**
